vim.api.nvim_create_user_command("Browse", require("git_browse").browse, {})
vim.api.nvim_create_user_command("Blame", require("git_browse").blame, {})
vim.api.nvim_create_user_command("BrowseLine", require("git_browse").browse_line, {})
vim.api.nvim_create_user_command("BlameLine", require("git_browse").blame_line, {})
vim.api.nvim_create_user_command("BrowseSelected", require("git_browse").browse_selected, {})
vim.api.nvim_create_user_command("BlameSelected", require("git_browse").blame_selected, {})
